### PR TITLE
Filtering detection based on confidence_score

### PR DESCRIPTION
**Pull request by rajgandhi1**
Added support to filter the detections based on the confidence_score of the detection.  The argument added is called **detection_score_threshold**.

### CODE REVIEW

**Comment by PolarNick239** [comment]
Thank you!

P.S. I disabled it by default, so that user can enable it only if needed. Also I moved filtration logic to the place where other filtrations are done.

**Comment by rajgandhi1** [comment]
Great Thanks!
Great script, this has helped a lot.
I was thinking of placing all the modifiable arguments as parser arguments. That way users will know what they have control over and also experiments will become much faster.

**Comment by PolarNick239** [comment]
In fact parameters that are necessary to be specified by final user are presented in GUI - https://github.com/rajgandhi1/metashape-scripts/blob/98aff9eb2dd0d3e2c909297a6a5178baa308c3e8/src/detect_objects.py#L993

But we try to minimize number of parameters that are shown to final user - because it can be hard to understand what parameters should be changed.

**Comment by rajgandhi1** [comment]
Understood Thanks.

**Pull request merged**
