### PR TITLE
Image_quality.py

### PR DESCRIPTION
**Pull request by PersaKouts**
"""
Metashape Image quality estimator Script (v 1.0)
Persa Koutsouradi, Feb 2023
Usage:
Workflow -> Batch Process -> Add -> Run script
This script estimates the quality of the images in a chunk.
When the image quality is less than 0.7, the image is removed form the chunk.

"""

import Metashape

# Checking compatibility
compatible_major_version = "1.8"
found_major_version = ".".join(Metashape.app.version.split('.')[:2])
if found_major_version != compatible_major_version:
    raise Exception("Incompatible Metashape version: {} != {}".format(found_major_version, compatible_major_version))

doc = Metashape.app.document
chunk = doc.chunk

quality_list = []

for camera in chunk.cameras:
    chunk.analyzePhotos(camera)
    if 'Image/Quality' in camera.meta:
        quality = float(camera.meta['Image/Quality'])
        if quality < 0.7:
            chunk.remove(camera)
        else:
            quality_list.append([camera.label, quality])

# Print the quality values for verification
print("Image quality values:")
print(quality_list)

### CODE REVIEW

**Comment by PolarNick239** [comment]
Hi, can you please check "Files changed (33)"?

1) It seems that PR is targeted into 1.8 branch, please, create a new PR into master branch (i.e. currently it is 2.0).
2) Please check that your repository was updated w.r.t. upstream commits - so that PR contains only your commit with your contribution.

**Comment by PersaKouts** [comment]
Hi! Thanks for your feedback. I am working on it now.
I have one question, since I am new to GitHub
I am at the contribution folder (master branch) and I am about to propose a new file, is that correct what I am doing?

**Comment by PolarNick239** [comment]
Yes.

**Comment by PersaKouts** [comment]
ok, thanks

**Pull request closed without merging**
